on:
  push:
    branches:
      - "*"
    paths:
      - "packages/**/*"
      - "build-packages"
      - ".github/workflows/build-packages.yaml"
    tags:
      - "packages@*"
    workflow_dispatch:

jobs:
  build-packages:
    runs-on: 'ubuntu-latest'
    name: 'run build'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'
      - name: 'Run the build'
        id: package-build
        run: |
          # CHANGE ME: this should use :main once main is functional
          ./build-packages --container-source=pull --container-tag=dev --verbose
      - name: 'Upload artifacts to temporary storage'
        uses: 'actions/upload-artifact@v3'
        with:
          name: "opentrons-python-packages"
          path: "dist/**/*"
