name: Upload to website

on:
  push:
    branches:
      - main
    # probably specify a dedicated directory for website content that needs to be uploaded to the bucket
    # When any changes is detected in this directory, it triggers this workflow. For instance, /web folder
    path:
      - '/index'

  # probably needed to specify which of the environment/buckets to upload contents
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to upload contents to
        type: environment
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  upload-dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    name: Uploading to dev website bucket
    environment: dev
      name: upload to dev bucket
      url: 'https://dev.pypi.opentrons.com'
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses; actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload web contents
        run: aws s3 sync ./index s3://${{secrets.AWS_S3_BUCKET}}
  

  upload-staging:
    if: ${{ github.event.inputs.environment == 'staging' }}
    name: Uploading to dev website bucket
    environment: staging
      name: upload to staging bucket
      url: 'https://staging.pypi.opentrons.com'
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses; actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload web contents
        run: aws s3 sync ./index s3://${{secrets.AWS_S3_BUCKET}}
      

  upload-prod:
    if: ${{ github.event.inputs.environment == 'prod' }}
    name: Uploading to production website bucket
    environment: prod
      name: upload to prod bucket
      url: 'https://pypi.opentrons.com'
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses; actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload web contents
        run: aws s3 sync ./index s3://${{secrets.AWS_S3_BUCKET}}

      